const work = [
  { company: 'GreenStone Farm Credit Services', title: 'Application Developer Intern', start: '01/01/2012', end: '10/01/2013', description: 'As an application developer intern, the majority of my time was spent working on small projects and learning. My primary focus was learning the .NET stack with razor templates (for MVC projects), and Bootstrap/jQuery for responsive components' },
  { company: 'Independent Contractor', title: 'Contractor', start: '10/01/2013', end: '08/30/2016', description: 'After leaving GreenStone Farm Credit services, I began to freelance. During this period of time I worked on a large variety of projects, including everything from tasks like router installations to website development. All web development done during this time was utilizing the .NET stack with an MVC structure.' },
  { company: 'Gordon Food Service', title: 'Application Developer', start: '08/30/2016', end: '07/01/2017', description: 'As an application developer at Gordon Food Services (GFS) I was responsible for maintaining existing applications, and occasionally adding new functionality. During my time at GFS I focused mostly on using the LAMP stack for development along with WordPress, and Drupal content management systems.' },
  { company: 'TeamDDM', title: 'Mobile Application Developer (Contractor)', start: '06/01/2018', end: '11/01/2018', description: 'My employment at TeamDDM took my development career in another direction temporarily. During my time at TeamDDM I was responsible for maintaining and developing mobile applications. I had the opportunity to work with a variety of mobile apps both native, and cross platform. Some of the notable technologies I worked with during this time are: Xamarin (cross platform development), Objective-C/Swift (native development), Java (native development), and the Universal Windows Platform (native development).' },
  { company: 'i2 Integration', title: 'Software Engineer', start: '11/01/2018', end: '08/01/2020', description: 'In November of 2018, i2 Integration hired me as a Software Engineer. Originally my primary responsibilites were maintaining an existing legacy application written with the .NET stack. Eventually I was brought on as a core member of the enterprise development team. During this time I worked on creating new enterprise web applications. These applications were written with a .NET backend using the DotNetNuke CMS. In addition, they utilized Vue frontends that leveraged custom Rest APIs written to integrate with DNN.' },
  { company: 'LexisNexis', title: 'Senior Software Engineer', start: '10/01/2020', end: '06/01/2021', description: 'After my employment at i2 Integration I transitioned to LexisNexis as a Senior Software Engineer. My core responsibilities were centered around building a new web application for the State of Michigan. This application utilized .NET with a traditional MVC project layout' },
  { company: 'Kunz, Leigh & Associates', title: 'Senior Software Engineer', start: '09/01/2021', end: null, description: 'When I transitioned to Kunz, Leigh & Associates (KL&A), I took another technology shift in my career path to learn Angular for frontend development. The applications I am responsible for building and maintaining still utilize many of the common concepts from my previous jobs (such as a .NET backend with Rest APIs)' }
]

export default work
